export const MATCHES =
    [
        {
            id: 0,
            team1: 'Bears',
            image1: 'assets/images/bears.png',
            team2: 'Lions',
            image2: 'assets/images/lions.png',
            cup: 'My Cup',
            date: '16/02/2021',
            hour: '10:00 am',
            place: 'New Curling Arena',
            result: '7-4',
        },
        /*{
            id: 1,
            team1: 'UC',
            image1: 'assets/images/uc.png',
            team2: 'Wildcats',
            image2: 'assets/images/wildcats.png',
            cup: 'My Cup',
            date: '23/02/2021',
            hour: '10:00 am',
            place: 'New Curling Arena',
            result: '7-6',
        },
        {
            id: 2,
            team1: 'Cruzeiro',
            image1: 'assets/images/cruzeiro.png',
            team2: 'Fluminense',
            image2: 'assets/images/fluminense.png',
            cup: 'My Cup',
            date: '30/02/2021',
            hour: '10:00 am',
            place: 'New Curling Arena',
            result: '5-4',
        },
        {
            id: 3,
            team1: 'Gremio',
            image1: 'assets/images/gremio.png',
            team2: 'International',
            image2: 'assets/images/internacional.png',
            cup: 'My Cup',
            date: '07/03/2021',
            hour: '10:00 am',
            place: 'New Curling Arena',
            result: '12-1',
        },
        {
            id: 4,
            team1: 'Palmeiras',
            image1: 'assets/images/palmeiras.png',
            team2: 'Lions',
            image2: 'assets/images/lions.png',
            cup: 'My Cup',
            date: '15/03/2021',
            hour: '10:00 am',
            place: 'New Curling Arena',
            result: '6-5',
        },*/
    ]