export const TOURNAMENTS =
    [
        {
            id: 0,
            name: 'OLYMPIC QUALIFICATION EVENT 2021',
            place: 'Leeuwarden, Netherlands',
            date: '5 - 18 December 2021',
            numberofteams: 9,
            prize: 'Qualification to the 2021 Olympics',
            state: 'Registrations Closed',
        },
        {
            id: 1,
            name: 'WORLD JUNIOR-B CURLING CHAMPIONSHIPS 2022',
            place: 'Lohja, Finland',
            date: '3 - 12 January 2022',
            numberofteams: 18,
            prize: 'Junior Cup',
            state: 'Registrations Closed',
        },
        {
            id: 2,
            name: ' WORLD MIXED DOUBLES QUALIFICATION EVENT 2022',
            place: 'Forfar, Scotland',
            date: '4 - 9 January 2022',
            numberofteams: 0,
            prize: 'World Mixed Doubles Cup',
            state: 'Cancelled',
        },
        {
            id: 3,
            name: 'WORLD QUALIFICATION EVENT 2022',
            place: 'Lohja, Finland',
            date: '17 - 22 January 2022',
            numberofteams: 0,
            prize: 'Qualification to the 2021 Olympics',
            state: 'Open Enrollment',
        },
        {
            id: 4,
            name: 'PARALYMPIC WINTER GAMES BEIJING 2022',
            place: 'Beijing, China',
            date: '5 - 12 March 2022',
            numberofteams: 0,
            prize: 'Gold, Silver and Copper Medal',
            state: 'Open Enrollment',
        },
        {
            id: 5,
            name: 'WORLD JUNIOR CURLING CHAMPIONSHIPS 2022',
            place: 'Jönköping, Sweden',
            date: '5 - 12 March 2022',
            numberofteams: 0,
            prize: 'World Junior Cup',
            state: 'Open Enrollment',
        },
        {
            id: 6,
            name: 'WORLD WOMEN’S CURLING CHAMPIONSHIP 2022',
            place: 'Prince George, Canada',
            date: '19 - 27 March 2022',
            numberofteams: 0,
            prize: 'World Women’s Cup',
            state: 'Open Enrollment',
        },
        {
            id: 7,
            name: 'LGT WORLD MEN’S CURLING CHAMPIONSHIP 2022',
            place: 'Las Vegas, Nevada',
            date: '2 - 10 April 2022',
            numberofteams: 0,
            prize: 'World Men’s Cup',
            state: 'Open Enrollment',
        },
        {
            id: 8,
            name: 'WORLD MIXED DOUBLES CURLING CHAMPIONSHIP 2022',
            place: 'Undefined',
            date: '23 - 30 April 2022',
            numberofteams: 0,
            prize: 'World Mixed Doubles Cup',
            state: 'Open Enrollment',
        },
        {
            id: 9,
            name: 'EUROPEAN CURLING CHAMPIONSHIPS 2022 C-DIVISION',
            place: 'Vilnius, Lithuania',
            date: '1 - 6 May 2022',
            numberofteams: 0,
            prize: 'European Cup',
            state: 'Open Enrollment',
        },
        {
            id: 10,
            name: 'OLYMPIC WINTER GAMES BEIJING 2022',
            place: 'Beijing, China',
            date: '3 - 20 February 2022',
            numberofteams: 0,
            prize: 'Gold, Silver, Copper Medals ',
            state: 'Open Enrollment',
        },
    ]
